### ISSUE TITLE
[Request]: use same secrets naming convention as in `exoscale-cloud-controller-manager`

### ISSUE THREAD

**Issue by thomas-chauvet** [exoscale/exoscale-csi-driver#6]
### Your request

In [exoscale-cloud-controller-manager](https://github.com/exoscale/exoscale-cloud-controller-manager) secrets contain:

- api-endpoint
- api-key
- api-secret

In CSI driver, secrets contain:

- EXOSCALE_API_KEY
- EXOSCALE_API_SECRET

Furthermore, secrets are passed as environment variables like [this](https://github.com/exoscale/exoscale-csi-driver/blob/main/deployment/exoscale-csi.yaml#L849-L851):

```yaml
          envFrom:
            - secretRef:
                name: exoscale-csi-credentials
```

But as I suggest to rename secrets, they could be passed like this:

```yaml
          - name: EXOSCALE_API_SECRET
            valueFrom:
              secretKeyRef:
                key: api-secret
                name: exoscale-credentials
          - name: EXOSCALE_API_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: api-endpoint
                name: exoscale-credentials
```

Finally, I suggest to rename secrets' name `exoscale-csi-credentials` to `exoscale-credentials`. Thus, the two components will be coherent which will facilitate the deployment.

Happy to make a PR if ok for you.

Cheers,

Thomas
