### ISSUE TITLE
[Feature Request]: Support `accessModes ReadWriteMany`

### ISSUE THREAD

**Issue by thomas-chauvet** [exoscale/exoscale-csi-driver#8]
### What feature would you like to have in the provider?

I've just tested to change `pvc.yaml` in example to use `ReadWriteMany` instead of `ReadWriteOnce`:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sbs-pvc
  namespace: awesome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: exoscale-sbs
```

I end up with an error to start the pod defined in `deployment.yaml`:

```txt
MountVolume.MountDevice failed for volume "pvc-ce3b02e3-40be-4423-b50b-2f17909e2300" : rpc error: code = InvalidArgument desc = volume ch-gva-2/cc1b1bb9-55dc-4643-bd50-a9de091b74a9 capability not supported
```

It seems it supports only `ReadWriteOnce`.

Is it planed in the future?

Thanks
